---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations: 
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: ConsulResolver
      name: consul-dc1
      address: consul-server.default.svc.cluster.local:8500
      datacenter: dc1
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          secret: sockshop-letsencrypt-cert  
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
    - port: 8443
      targetPort: 8443
      nodePort: 30043
      name: https
  selector:
    service: ambassador
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-admin
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8877
      targetPort: 8877
      nodePort: 30087
  selector:
    service: ambassador  
