---
apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30085
  selector:
    app: consul
    component: server  
