---
apiVersion: v1
kind: Service
metadata:
  name: front-end-nodeport
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  front-end_mapping
      prefix: /socks/
      service: front-end-proxy
      resolver: consul-dc1
      tls: ambassador-consul
      load_balancer:
        policy: round_robin
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  fallback_mapping
      prefix: /
      service: front-end-proxy
      resolver: consul-dc1
      tls: ambassador-consul
      load_balancer:
        policy: round_robin
spec:
  type: NodePort
  selector:
    name: front-end
  ports:
  - port: 80
    name: http
